CREATE TABLE applicant
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_number VARCHAR(11) PRIMARY KEY UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    monthly_income INT(50) NOT NULL,
    phone_number VARCHAR(13) NOT NULL
);


INSERT INTO applicant(id_number, first_name, last_name, monthly_income, phone_number)
VALUES ('12345678900', 'Ahmet', 'Yılmaz', 3500, '05351234560'),
       ('12345678901', 'Mehmet', 'Şahin', 5800, '05351234561'),
       ('12345678902', 'Hasan', 'Ali', 3700, '05351234562'),
       ('12345678903', 'Merve', 'Solmaz', 11000, '05351234563'),
       ('12345678904', 'Cansu', 'Kara', 4700, '05351234564'),
       ('12345678905', 'Aylin', 'Budak', 5200, '05351234565'),
       ('12345678906', 'Mert', 'Aydın', 8400, '05351234566'),
       ('12345678907', 'Kader', 'Arslan', 4300, '05351234567'),
       ('12345678908', 'Tolga', 'Sönmez', 3100, '05351234568'),
       ('12345678909', 'Canan', 'Sezgin', 6200, '05351234569');